{
 "title": "Datastores Health",
 "tags": [
  "datastores",
  "infra"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Postgres: Active Connections",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pg_stat_activity_count" }
   ]
  },
  {
   "title": "Redis: Cache Hit Ratio",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(rate(redis_keyspace_hits_total[5m]) / (rate(redis_keyspace_hits_total[5m]) + rate(redis_keyspace_misses_total[5m]))) * 100"
    }
   ]
  },
  {
   "title": "OpenSearch: Cluster Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_status"
    }
   ]
  },
  {
   "title": "Kafka: Brokers Up",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "kafka_brokers" }
   ]
  }
 ]
}