[SERVICE]
    Flush         1
    Daemon        Off
    Log_Level     info
    Parsers_File  /fluent-bit/etc/parsers.conf

[INPUT]
    Name          forward
    Listen        0.0.0.0
    Port          24224

[FILTER]
    Name          parser
    Match         *
    Key_Name      log
    Parser        json_message
    Reserve_Data  On
    Preserve_Key  On

[FILTER]
    Name          grep
    Match         *
    Exclude       log actuator/health
    Exclude       log /_cluster/health

[FILTER]
    Name          record_modifier
    Match         *
    Record        environment production
    Record        stack marketplace-search-system

[OUTPUT]
    Name                  opensearch
    Match                 *
    Host                  open-search
    Port                  9200
    Index                 marketplace-logs
    Logstash_Format       On
    Logstash_Prefix       marketplace-logs
    Logstash_DateFormat   %Y.%m.%d
    Generate_ID           On
    Retry_Limit           3
    tls                   Off
    tls.verify            Off
    Suppress_Type_Name    On
    Trace_Error           Off
