# Parser padrão para logs do Docker daemon (formato JSON com campo "log")
[PARSER]
    Name        docker
    Format      json
    Time_Key    time
    Time_Format %Y-%m-%dT%H:%M:%S.%L
    Time_Keep   On

# Parser para desempacotar o campo "log" como JSON estruturado
# Captura os campos: level, msg/message, trace_id, span_id, logger, timestamp etc.
[PARSER]
    Name        json_message
    Format      json
    Time_Key    ts
    Time_Format %Y-%m-%dT%H:%M:%S.%L%z

[PARSER]
    Name        springboot
    Format      regex
    Regex       /^\x1b\[2m(?<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2})\x1b\[0;39m \x1b\[35m\[(?<thread>.*)\]\x1b\[0;39m \x1b\[(34|33|31)m(?<level>[A-Z ]{5})\x1b\[0;39m \x1b\[36m(?<logger>.*)\x1b\[0;39m - (?<message>.*)$/

[PARSER]
    Name        python
    Format      regex
    Regex       /^(?<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) - (?<logger>.*) - (?<level>[A-Z]*) - \[(?<trace_id>[a-f0-9]*):(?<span_id>[a-f0-9]*)\] - \[(?<location>.*)\] - (?<message>.*)$/
