<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>com.marketplace.search</groupId>
		<artifactId>search-system</artifactId>
		<version>1.0.0-SNAPSHOT</version>
		<relativePath>../pom.xml</relativePath>
	</parent>

	<groupId>com.marketplace.search.indexing</groupId>
	<artifactId>indexing-service</artifactId>
	<packaging>pom</packaging>
	<name>Indexing Service</name>
	<description>Serviço de indexcacao de produtos</description>

	<modules>
		<module>domain</module>
		<module>application</module>
		<module>infrastructure</module>
		<module>bootstrap</module>
	</modules>


	<dependencyManagement>
		<dependencies>

			<dependency>
				<groupId>com.marketplace.search.indexing</groupId>
				<artifactId>domain</artifactId>
				<version>${project.version}</version>
			</dependency>

			<dependency>
				<groupId>com.marketplace.search.indexing</groupId>
				<artifactId>application</artifactId>
				<version>${project.version}</version>
			</dependency>

			<dependency>
				<groupId>com.marketplace.search.indexing</groupId>
				<artifactId>infrastructure</artifactId>
				<version>${project.version}</version>
			</dependency>

			<dependency>
				<groupId>com.marketplace.search.indexing</groupId>
				<artifactId>bootstrap</artifactId>
				<version>${project.version}</version>
			</dependency>

		</dependencies>

	</dependencyManagement>

</project>