apiVersion: 1

datasources:
  - name: OpenSearch Logs
    type: grafana-opensearch-datasource
    uid: opensearch-logs
    access: proxy
    url: http://open-search:9200
    isDefault: false
    editable: true
    jsonData:
      database: "marketplace-logs-*"
      timeField: "@timestamp"
      version: "2.0.0"
      flavor: opensearch
      logMessageField: log
      logLevelField: level
      maxConcurrentShardRequests: 5
