# Configuração estática do Traefik
api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":8888"
  websecure:
    address: ":443"
  metrics:
    address: ":8082"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: marketplace-network
  file:
    directory: /etc/traefik
    watch: true

log:
  level: INFO
  format: json

accessLog:
  format: json

metrics:
  prometheus:
    entryPoint: metrics
    addEntryPointsLabels: true
    addServicesLabels: true
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0
